### PR TITLE
Fix StridedView type piracy

### LINKED ISSUE #27: StridedView type piracy
The following line:

https://github.com/chengchingwen/Pickle.jl/blob/f36db91d5ea75ffe4f16d1cc8c010b8c3a5a77a4/src/torch/torch_save.jl#L37

is type piracy. 

It's also not necessary, since this method was recently added  in Strided.jl:

https://github.com/Jutho/Strided.jl/blob/10cc9872f5b994d5f906c0ef0f28cef77ddd2683/src/stridedview.jl#L35

As a result, loading this package results in a warning:

> WARNING: Method definition (::Type{Strided.StridedView{T, N, A, F} where F<:Union{typeof(Base.adjoint), typeof(Base.conj), typeof(Base.identity), typeof(Base.transpose)} where A<:(DenseArray{T, N} where N where T) where N where T})(Base.PermutedDimsArrays.PermutedDimsArray{T, N, perm, iperm, AA} where AA<:(AbstractArray{T, N} where N where T) where iperm) where {T, N, perm} in module Strided at /home/cossio/.julia/packages/Strided/LvYNZ/src/stridedview.jl:35 overwritten in module Torch at /home/cossio/.julia/packages/Pickle/iHRCQ/src/torch/torch_save.jl:37.

Can we remove this line?

### PR DESCRIPTION
**Pull request by cossio**
Closes #27.

### CODE REVIEW

**Comment by cossio** [comment]
The failure on Julia nightly looks unrelated to this PR.

CI is also failing on Julia 1.3 because it cannot satisfy all compats. Is there a reason to support v1.3 here, instead of the LTs 1.6?

**Comment by cossio** [comment]
Strided.jl is requiring Julia >= 1.4, so I bumped the minimum Julia version here to 1.4 instead of 1.3. With that CI should pass.

**Comment by chengchingwen** [comment]
> Is there a reason to support v1.3 here, instead of the LTs 1.6?

Simply because I didn't remove that one, I think we could just drop the support below 1.6.

**Comment by cossio** [comment]
Okay, can you retrigger CI?

**Comment by chengchingwen** [comment]
Thanks!

**Pull request merged**
